### ISSUE TITLE
UnboundLocalError in Python 2.7

### ISSUE THREAD

**Issue by Eleeleth** [Atrolantra/Toribash-Market-Checker#3]
```
-> % python market_value_checker.py
Enter your username (of the account to do the market crawling): eleeleth
Enter your password (of the account to do the market crawling): <snip>
Failed to login. Please enter your details again.

Enter your username (of the account to do the market crawling): eleeleth
Enter your password (of the account to do the market crawling): <snip>
Traceback (most recent call last):
  File "market_value_checker.py", line 113, in <module>
    token = loginPart(session)
  File "market_value_checker.py", line 46, in loginPart
    return token
UnboundLocalError: local variable 'token' referenced before assignment
```

**Comment by Eleeleth** [comment]
This only happens if you fail to login once.
